export const userName = "Killian Lacaque";

export const galleryItems = [
  { 
    id: 1, 
    title: 'Traversée de l\'Islande', 
    description: "Traversée de l’Islande réalisée en 2023, du sud au nord, de la mer à la mer. \nUne distance de 480 km parcourue en 21 jours, en autonomie totale, sans ravitaillement.",
    imageUrl: '/images/gallery/islande.jpg',
    category: 'passion',
    color: '#8C8880',
  },
  {
    id: 2,
    title: 'Culturæ',
    description: "Jeu de culture générale structuré autour de 10 thèmes, proposant environ 6 500 questions accompagnées de leurs explications. \nUn système de statistiques détaillées et la création de comptes utilisateurs permettent de suivre et d’analyser sa progression.",
    imageUrl: '/images/gallery/culturae.jpg',
    category: 'projet',
    color: '#C0C6D1',
    url: 'https://culturae-app.vercel.app',
  },
  {
    id: 3,
    title: 'Novia',
    description: "Résolution de missions du jeu The Crew (IELLO) par algorithme ou intelligence artificielle basée sur le Q-Learning. \nLes missions et la distribution des cartes sont configurables, de façon manuelle ou aléatoire.",
    imageUrl: '/images/gallery/novia.jpg',
    category: 'projet',
    color: '#1F438C',
    url: 'https://novia-ai.vercel.app',
  },
  {
    id: 4,
    title: 'I Have Read.',
    description: "Accepter des conditions générales d’utilisation en résolvant des énigmes et missions. \nChaque défi sert de contrainte pour valider l’acceptation.",
    imageUrl: '/images/gallery/ihaveread.jpg',
    category: 'projet',
    color: '#E6E7EB',
    url: 'https://i-have-read.vercel.app',
  },
  {
    id: 5,
    title: 'What Remains',
    description: "Une expérience visuelle et sonore qui illustre l’impact de l’humain sur la nature. \nPollution, déforestation, production ou consommation... autant de thèmes pour sensibiliser.",
    imageUrl: '/images/gallery/whatremains.jpg',
    category: 'projet',
    color: '#A6A6A6',
    url: 'https://what-remains-app.vercel.app',
  },
  { 
    id: 6,
    title: 'Arbre Généalogique', 
    description: "Une exploration immersive sur 12 générations. \nRedécouvre l'histoire familiale sous un autre angle grâce aux filtres dynamiques : métiers, lieux et longévité colorent le parcours de nos ancêtres.",
    imageUrl: '/images/gallery/arbre.jpg',
    category: 'passion',
    color: '#5E778C',
  },
];